### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Zizzzzzzz** [YuHengsss/MSVMamba#4]
Thank you for your excellent work. I would like to inquire about how to obtain the visualized results of Figures 2 and 4 from the paper.

**Comment by YuHengsss** [comment]
Thanks for your attention on our work. The code related to the visualization can be found here:
https://github.com/YuHengsss/MSVMamba/blob/master/analyze/attnmap.py

**Comment by Zizzzzzzz** [comment]
Thanks! I will try it.
