### ISSUE TITLE
关于decay可视化的问题

### ISSUE THREAD

**Issue by renyulin-f** [YuHengsss/MSVMamba#5]
您好! 想请教一下文中提到了对exp(delta_A)进行可视化.
请问这里对应的是代码中的A_logs嘛,其维度为(4*d_inner, d_state), 这个该如何计算并绘制图片呢, 即不同scan routes的热力图

**Comment by YuHengsss** [comment]
Please refer to code here: https://github.com/YuHengsss/MSVMamba/blob/201eaac16b9020c1523b0fcd1bfbebb6615a043b/analyze/attnmap.py#L654C183-L654C192

These dimensions will be averaged when plotting the decay map.
